[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    
[build]
  command = "npm run build"
  publish = "client/dist"

[[plugins]]
  package = "@netlify/plugin-functions-core"